#+TITLE: 二次量子化笔记
#+DATE: <2018-09-27>
#+CATEGORIES: 专业笔记
#+TAGS: 物理, 量子力学, 二次量子化
#+HTML: <!-- toc -->
#+HTML: <!-- more -->
* 单体力学量

** 本征表象

$N$ 个粒子组成的系统，对于单个粒子的力学量 $\hat{f}$ ，其第 $i$ 个本征值为 $f_i$ ，本征态为 $\mid i \rangle$ ，即
\begin{align*}
\hat{f} \mid i \rangle = f_i \mid i \rangle
\end{align*}
那么这 $N$ 个粒子就是：
\begin{align*}
\hat{F} = \sum_i f_i \hat{n_i} = \sum_i f_i a_i^{\dagger}a_i
\end{align*}
$a_i^{\dagger}$ 是 $f$ 的本征表象中的产生算符。

** 非本征表象

若要写出非本征表象下的形式，则应对 $a_i^{\dagger}$ 做表象变换。 $a_i^{\dagger}$ 的表象变换可让 $a_i^{\dagger}$ 作用在真空态上如下导出：
\begin{align*}
a_i^{\dagger} \mid 0 \rangle = \mid i \rangle = \sum_{\alpha} \mid \alpha \rangle\langle \alpha \mid i \rangle = \sum_{\alpha} a_{\alpha}^{\dagger}\mid 0 \rangle \langle \alpha \mid i \rangle
\end{align*}

所以可得:
\begin{align*}
a_i^{\dagger}   = \sum_{\alpha} a_{\alpha}^{\dagger}\ \langle \alpha \mid i \rangle
\end{align*}
如此看来, 产生算符的表象变换类似于一个右矢, 而消灭算符的表象变换类似于一个左矢. 便于记忆可以认为将 $a_i^{\dagger} \mid 0\rangle$ 简记为了 $a_i^{\dagger}$ ,将  $a_{\alpha}^{\dagger} \mid 0\rangle$ 简记为了 $a_{\alpha}^{\dagger}$. 产生算符作用在右矢空态上才不为零.

那么:
\begin{align*}
\hat{F} =& \sum_i f_i a_i^{\dagger}a_i \\
=& \sum_i \sum_{\alpha \beta} f_i \cdot a_{\alpha}^{\dagger}\langle \alpha \mid i \rangle \cdot \langle i \mid \beta \rangle a_{\beta} \\
=& \sum_i \sum_{\alpha \beta}  \cdot a_{\alpha}^{\dagger}\langle \alpha \mid f_i\mid i \rangle \cdot \langle i \mid \beta \rangle a_{\beta} \\
=& \sum_i \sum_{\alpha \beta}  \cdot a_{\alpha}^{\dagger}\langle \alpha \mid \hat{f}\mid i \rangle \cdot \langle i \mid \beta \rangle a_{\beta} \\
=& \sum_{\alpha \beta}   a_{\alpha}^{\dagger}\langle \alpha \mid \hat{f} \mid \beta \rangle a_{\beta} \\
=& \sum_{\alpha \beta}  \langle \alpha \mid \hat{f} \mid \beta \rangle a_{\alpha}^{\dagger} a_{\beta}
\end{align*}

我为了便于理解, 直接将产生消灭算符看成是多体表象中的基矢, 产生算符是右矢, 消灭算符是左矢. 那么, 一切就都说得通了:
\begin{align*}
\hat{F} \sim \sum_{\alpha \beta}  \langle \alpha \mid \hat{f} \mid \beta \rangle \cdot \mid \alpha \rangle \langle \beta \mid
\end{align*}
为什么是这样, 我也不知道.

* 二体力学量

** 本征表象

同样的, $N$ 个粒子组成的系统, 于单个粒子的力学量 $\hat{f}$ ，其第 $i$ 个本征值为 $f_i$ ，本征态为 $\mid i \rangle$ ，即
\begin{align*}
\hat{f} \mid i \rangle = f_i \mid i \rangle
\end{align*}
考虑两个粒子间的相互作用,  假设分别在态 $\mid i \rangle$  和 态 $\mid j \rangle$ 上 ,其相互作用的算符为:
\begin{align*}
\hat{u} = \hat{u}(\hat{f}_i, \hat{f}_j)
\end{align*}
即有:
\begin{align*}
\hat{u}(\hat{f}_i, \hat{f}_j) \mid i,j\rangle = u_{ij} \mid i,j \rangle
\end{align*}
其中:
\begin{align*}
\mid i,j \rangle = \mid i \rangle \otimes \mid j \rangle = \mid i \rangle  \mid j \rangle
\end{align*}
表示态 $\mid i \rangle$  和 态 $\mid j \rangle$ 上各有一个粒子.

那么这 $N$ 个粒子之间所有的两两相互作用就是：
\begin{align*}
\hat{U} = \frac{1}{2} \sum_{i\ne j} u_{ij} \hat{n}_i \hat{n}_j + \frac{1}{2}\sum_i u_{ii} \hat{n}_i(\hat{n}_i - 1)
\end{align*}
第一项表示单粒子态 $\mid i \rangle$ 上有 $n_i$ 个粒子, 单粒子态 $\mid j \rangle$ 上有 $n_j$ 个粒子,  $n_i$ 个粒子和 $n_j$ 个粒子之间的两两相互作用一共是 $u_{ij} n_i n_j$, 然后就是对所有的态求和. 第二项是第一项中没有考虑的相同的态上不同粒子之间的相互作用. 每对粒子之间的相互作用都算了两次, 所以要除以二.

还可以写成另一种形式.
\begin{align*}
\hat{U} = \frac{1}{2} \sum_{i j} u_{ij} (\hat{n}_i \hat{n}_j - \delta_{ij} \hat{n}_i)
\end{align*}
第二项是考虑的相同的态上不同粒子之间的相互作用, 因为第一项中计算了两次, 所以要减去一次. 这个形式可以用对易关系进化简:
\begin{align*}
\hat{n}_i \hat{n}_j - \delta_{ij} \hat{n}_i =& a_i^{\dagger}a_i a_j^{\dagger}a_j -\delta_{ij} a_i^{\dagger}a_i \\
=& a_i^{\dagger}a_i a_j^{\dagger}a_j -\delta_{ij} a_i^{\dagger}a_j\\
=& a_i^{\dagger}a_i a_j^{\dagger}a_j -[a_i,a_j^{\dagger}]_{\mp} a_i^{\dagger}a_j \\
=& a_i^{\dagger} (a_i a_j^{\dagger}-[a_i,a_j^{\dagger}]_{\mp})a_j \\
=& a_i^{\dagger} (\pm a_j^{\dagger}a_i )a_j \\
=& a_i^{\dagger} a_j^{\dagger} (\pm a_i a_j) \\
=& a_i^{\dagger} a_j^{\dagger}  a_j a_i
\end{align*}

所以:
\begin{align*}
\hat{U} = \frac{1}{2} \sum_{i j} u_{ij} a_i^{\dagger} a_j^{\dagger}  a_j a_i
\end{align*}

** 非本征表象

与单体力学量类似的, 直接对本征表象的结果做表象变换:
\begin{align*}
\hat{U} =& \frac{1}{2} \sum_{i j} \sum_{\alpha \beta \gamma \delta}u_{ij} a_i^{\dagger} a_j^{\dagger}  a_j a_i  \\
=& \frac{1}{2} \sum_{i j}\sum_{\alpha \beta \gamma \delta} u_{ij} \cdot a_{\alpha}^{\dagger}\langle \alpha \mid i \rangle\cdot a_{\beta}^{\dagger}\langle \beta\mid j \rangle\cdot   \langle j \mid \gamma \rangle  a_{\gamma} \cdot \langle i\mid \delta \rangle a_{\delta} \\
=& \frac{1}{2} \sum_{i j}\sum_{\alpha \beta \gamma \delta} u_{ij} \cdot a_{\alpha}^{\dagger}a_{\beta}^{\dagger} a_{\gamma}  a_{\delta}\langle \alpha \mid i \rangle\cdot \langle \beta\mid j \rangle\cdot   \langle j \mid \gamma \rangle  \cdot \langle i\mid \delta \rangle  \\
=& \frac{1}{2} \sum_{i j} \sum_{\alpha \beta \gamma \delta} a_{\alpha}^{\dagger}a_{\beta}^{\dagger} a_{\gamma}  a_{\delta}\cdot \langle \alpha \mid\langle \beta\mid\cdot \left( u_{ij}\mid i \rangle \mid j \rangle   \langle j \mid \langle i\mid\right)\cdot \mid\gamma \rangle \mid \delta \rangle  \\
=& \frac{1}{2} \sum_{i j} \sum_{\alpha \beta \gamma \delta} a_{\alpha}^{\dagger}a_{\beta}^{\dagger} a_{\gamma}  a_{\delta}\cdot \langle \alpha \mid\langle \beta\mid\cdot \left( \hat{u}\mid i \rangle \mid j \rangle   \langle j \mid \langle i\mid\right)\cdot \mid\gamma \rangle \mid \delta \rangle  \\
=& \frac{1}{2}  \sum_{\alpha \beta \gamma \delta} a_{\alpha}^{\dagger}a_{\beta}^{\dagger} a_{\gamma}  a_{\delta}\cdot \langle \alpha \mid\langle \beta\mid \hat{u}\mid\gamma \rangle \mid \delta \rangle
\end{align*}

同样, 直接将产生消灭算符看成是多体表象中的基矢:
\begin{align*}
\hat{U} \sim \frac{1}{2}  \sum_{\alpha \beta \gamma \delta} \mid\alpha \rangle \mid \beta \rangle \langle \gamma \mid\langle \delta\mid\cdot \langle \alpha \mid\langle \beta\mid \hat{u}\mid\gamma \rangle \mid \delta \rangle
= \frac{1}{2}  \sum_{\alpha \beta \gamma \delta} \mid\alpha , \beta \rangle \langle \gamma ,\delta\mid\cdot \langle \alpha, \beta\mid \hat{u}\mid\gamma , \delta \rangle
\end{align*}

* 致谢

感谢 Qiang Han 老师的课件提供的主要思路.

感谢 J. J. Sakurai & Jim Napolitano 的 Modern Quantum Mechanics 一书提供的二体力学量在本征表象的二次量子化化简过程.
