#+TITLE: 多体物理读书会:5.1节 从Dirac表象中的演化算符到因果格林函数-通往diagram techniques之路
#+DATE: <2018-12-13>
#+CATEGORIES: 专业笔记
#+TAGS: 物理, 多体物理读书会, Dirac 表象, 演化算符, 格林函数, Feynman graphs, 因果格林函数
#+HTML: <!-- toc -->
#+HTML: <!-- more -->

* 起点

digram techniques 的起点是
\begin{align}
\label{eq:startpoint}
\boxed{U_D(t,t') = T_D \left\{ e^{\frac{1}{\mathrm{i}\hbar} \int_{t'}^t \mathrm{d}t'' V_{t''}^D(t'')} \right\}}
\end{align}
把它写成级数求和的形式
\begin{align}
U_D(t,t') = \sum_{n=0}^{\infty}\frac{1}{n!} \left( \frac{1}{\mathrm{i}\hbar} \right)^n \int_{t'}^t \mathrm{d}t_1 \cdots \int_{t'}^t \cdot \mathrm{d}t_n
\cdot T_{\varepsilon}\left\{ V_D(t_1) V_D(t_2 ) \cdots V_D(t_n) \right\}
\end{align}

* 因果格林函数

第三章中因果格林函数的定义为
\begin{align*}
G_{AB}^c (t-t') \equiv - \mathrm{i} \langle T_{\varepsilon} (A(t)B(t'))\rangle
\end{align*}
如果是有相互作用的零温系统变为
\begin{align}
\label{eq:cgf}
\mathrm{i}G_{AB}^c (t-t') = \langle E_0 | T_{\varepsilon} (A(t)B(t'))| E_0 \rangle
\end{align}

* 绝热演化得到基态

如 Dirac 表象的设定, 系统的 Hamiltonia 可以分为无相互作用 Hamiltonian $H_0$ 加上相互作用 Hamiltonian $V_t$ .
这里假设相互作用 Hamiltonian $V_t$ 的形式为 $V e^{-\alpha |t|}\,\,(\alpha>0)$ ,所以 Hamiltonian 为
\begin{align}
H = H_0 + V e^{-\alpha |t|} \quad \quad ,\alpha>0
\end{align}
也就是说相互作用的含时包含在一个衰减因子中. 相互作用在 $t=0$ 时为 $V$ ,在 $t=\pm \infty$ 时为 $0$ .

接下来在 Dirac 表象中考虑这个问题. 定义 Dirac 表象中 $t_0=0$ . 系统在 $t=\pm \infty$ 时为无相互作用系统基态.
在 Dirac 表象中, 会有一个相位因子, 记加入此相因子后此态为
\begin{align}
| \psi_{\alpha}^D (t \to \infty) \rangle = | \eta_0 \rangle
\end{align}
根据 Gell-Mann–Low 定理, 以及论证和假设, 得到在 $t=0$ 时刻, Hamiltonian 为 $H = H_0+V$ 的系统的基态为
\begin{align}
| \tilde{E}_0 \rangle = \lim _{\alpha \to 0} \frac{U_{\alpha}^D (0,-\infty) |\eta_0\rangle}
{\langle \eta_0 | U_{\alpha}^D(0,-\infty)|\eta_0\rangle}
\end{align}
意思就是说系统从无相互作用的基态开始, 无穷缓慢 $(\alpha \to 0)$ 地加入相互作用, 系统最终会达到有相互作用系统的基态.
加入一个分母是为了消除 $U_{\alpha}^D(0,-\infty)|\eta_0\rangle$ 中发散的相位. 但是 $| \tilde{E}_0 \rangle$
是未归一化的.

* 正负无穷处的等价性

** 问题引入

先把 $A(t)B(t')$ 换到 Dirac 表象(把相互作用的演化去掉即可)
\begin{align}
A(t)B(t') = U^D(0,t) A^D(t) U^D(t,t') B^D(t') U^D(t',0)
\end{align}
最终要算的目标是式 \eqref{eq:cgf} , 将绝热演化得到的基态代入其中, 并进行归一化
\begin{align*}
\mathrm{i} G_{AB}^c (t-t') =& \frac{ \langle \tilde{E}_0 | T_{\varepsilon}(U^D(0,t) A^D(t) U^D(t,t') B^D(t') U^D(t',0)) |\tilde{E}_0 \rangle}{\langle \tilde{E}_0 |\tilde{E}_0 \rangle}\\
=& \lim_{\alpha \to 0} \frac{\langle \eta_0| U_{\alpha}^D(-\infty ,0) T_{\varepsilon}(U^D(0,t) A^D(t) U^D(t,t') B^D(t') U^D(t',-\infty))| \eta_0\rangle}
{\langle \eta_0| U_{\alpha}^D(-\infty ,0)  U_{\alpha}^D(0, -\infty)| \eta_0\rangle}\\
=& \lim_{\alpha \to 0} \langle \eta_0| U_{\alpha}^D(-\infty ,t) T_{\varepsilon}( A^D(t) U^D(t,t') B^D(t'))  U_{\alpha}^D(t', -\infty)| \eta_0\rangle
\end{align*}
然后将演化算符的具体形式代入(对于费米子来说, $T_D, \quad T_{\varepsilon}$ 是等价的)
\begin{align*}
& U_{\alpha}^D(-\infty ,0) T_{\varepsilon}(A(t)B(t')) U_{\alpha}^D(0, -\infty) \\
=& \sum_{n=0}^{\infty}\frac{1}{n!} \left( \frac{1}{\mathrm{i}\hbar} \right)^n \int^{-\infty}_t \mathrm{d}t_1 \cdots \int^{-\infty}_t \cdot \mathrm{d}t_n
\cdot T_{\varepsilon}\left\{ V_D(t_1) V_D(t_2 ) \cdots V_D(t_n) \right\}  \cdot e^{-\alpha(|t_1|+\cdots| t_n|)}\\
&\sum_{l=0}^{\infty}\frac{1}{l!} \left( \frac{1}{\mathrm{i}\hbar} \right)^l \int_{t'}^t \mathrm{d}\tilde{t}_1 \cdots \int_{t'}^t \cdot \mathrm{d}\tilde{t}_l
\cdot T_{\varepsilon}\left\{A_D(t) V_D(\tilde{t}_1) V_D(\tilde{t}_2 ) \cdots V_D(\tilde{t}_l)B_D(t') \right\} \cdot e^{-\alpha(|\tilde{t}_1| +\cdots |\tilde{t}_l| )}\\
&\cdot \sum_{m=0}^{\infty}\frac{1}{m!} \left( \frac{1}{\mathrm{i}\hbar} \right)^m \int^{t'}_{-\infty} \mathrm{d}\bar{t}_1 \cdots \int_{-\infty}^{t'} \cdot \mathrm{d}\bar{t}_m
\cdot T_{\varepsilon}\left\{ V_D(\bar{t}_1) V_D(\bar{t}_2 ) \cdots V_D(\bar{t}_m) \right\} \cdot e^{-\alpha(|\bar{t}_1| + \cdots| \bar{t}_m|)}\\
=& \sum_{n,m,l=0}^{\infty}\frac{1}{n!m!l!} \left( \frac{1}{\mathrm{i}\hbar} \right)^{n+m+l} \cdot \int^{-\infty}_t \mathrm{d}t_1 \cdots \int^{-\infty}_t \cdot \mathrm{d}t_n
\cdot \int_{t'}^t \mathrm{d}\tilde{t}_1 \cdots \int_{t'}^t \cdot \mathrm{d}\tilde{t}_l \cdot \int^{t'}_{-\infty} \mathrm{d}\bar{t}_1 \cdots \int_{-\infty}^{t'} \cdot \mathrm{d}\bar{t}_m \\
&\cdot T_{\varepsilon}\left\{ V_D(t_1) V_D(t_2 ) \cdots V_D(t_n) \right\} \cdot T_{\varepsilon}\left\{A_D(t) V_D(\tilde{t}_1) V_D(\tilde{t}_2 ) \cdots V_D(\tilde{t}_l)B_D(t') \right\}
\cdot T_{\varepsilon}\left\{ V_D(\bar{t}_1) V_D(\bar{t}_2 ) \cdots V_D(\bar{t}_m) \right\} \\
&\cdot e^{-\alpha(|t_1|+\cdots |t_n| +|\tilde{t}_1| +\cdots |\tilde{t}_l| +|\bar{t}_1| + \cdots |\bar{t}_m|)}
\end{align*}
如果这样做, 故事就此结束.

如果第一个 $-\infty$ 换成 $+\infty$ ,或许可以将三个 time-ordering 合并.

** 等价性的说明

假设通过 Gell-Mann–Low 定理,并且假设相互作用系统的基态没有简并以及其它论证和假设同样可以得到以下态也是有相互作用系统的基态(对此细节推导有疑问).
\begin{align}
| \tilde{E}_0' \rangle = \lim _{\alpha \to 0} \frac{U_{\alpha}^D (0,+\infty) |\eta_0\rangle}
{\langle \eta_0 | U_{\alpha}^D(0,+\infty)|\eta_0\rangle}
= e^{\mathrm{i}\phi} |\tilde{E}_0 \rangle
\end{align}
它和之前从 $t = -\infty$ 得到的 $|\tilde{E}_{0} \rangle$ 只差一个相位.
首先, 从直觉上来说, 由于相互作用势对于时间的因子 $|\alpha|$ 中含有绝对值, 因此它和 $|\tilde{E}_0\rangle$ 应该是等价的.

但是
\begin{align}
\langle \eta_0 |\tilde{E}_0 \rangle = \langle \eta_0 |\tilde{E}_0' \rangle = 1
\end{align}
所以我们可以用 $\langle \tilde{E}_0' |$ 替换 $\langle \tilde{E}_0' |$ . 故事可以继续进行.

* 三个 time-ordering 的合并

我们用 $\langle \tilde{E}_0' |$ 替换 $\langle \tilde{E}_0' |$ 后, 就有
\begin{align*}
\mathrm{i} G_{AB}^c (t-t') =& \frac{ \langle \tilde{E}_0' | T_{\varepsilon}(A(t)B(t')) |\tilde{E}_0 \rangle}{\langle \tilde{E}_0 |\tilde{E}_0' \rangle}\\
=& \lim_{\alpha \to 0} \frac{\langle \eta_0| U_{\alpha}^D(+\infty ,0) T_{\varepsilon}(U^D(0,t) A^D(t) U^D(t,t') B^D(t') U^D(t',-\infty))| \eta_0\rangle}
{\langle \eta_0| U_{\alpha}^D(+\infty, -\infty)| \eta_0\rangle}
\end{align*}
其中
\begin{align*}
& U_{\alpha}^D(+\infty ,0) T_{\varepsilon}(U^D(0,t) A^D(t) U^D(t,t') B^D(t') U^D(t',-\infty)) \\
=& \sum_{n,m,l=0}^{\infty}\frac{1}{n!m!l!} \left( \frac{1}{\mathrm{i}\hbar} \right)^{n+m+l} \cdot \int^{+\infty}_t \mathrm{d}t_1 \cdots \int^{ +\infty}_t \cdot \mathrm{d}t_n
\cdot \int_{t'}^t \mathrm{d}\tilde{t}_1 \cdots \int_{t'}^t \cdot \mathrm{d}\tilde{t}_l \cdot \int^{t'}_{-\infty} \mathrm{d}\bar{t}_1 \cdots \int_{-\infty}^{t'} \cdot \mathrm{d}\bar{t}_m \\
&\cdot T_{\varepsilon}\left\{ V_D(t_1) V_D(t_2 ) \cdots V_D(t_n) \right\} \cdot T_{\varepsilon}\left\{A_D(t) V_D(\tilde{t}_1) V_D(\tilde{t}_2 ) \cdots V_D(\tilde{t}_l)B_D(t') \right\}
\cdot T_{\varepsilon}\left\{ V_D(\bar{t}_1) V_D(\bar{t}_2 ) \cdots V_D(\bar{t}_m) \right\} \\
&\cdot e^{-\alpha(|t_1|+\cdots |t_n| +|\tilde{t}_1| +\cdots| \tilde{t}_l| +|\bar{t}_1| + \cdots| \bar{t}_m|)}\\
=& \sum_{n,m,l=0}^{\infty}\frac{1}{n!m!l!} \left( \frac{1}{\mathrm{i}\hbar} \right)^{n+m+l} \cdot \int^{+\infty}_{-\infty} \mathrm{d}t_1 \cdots \int^{ +\infty}_{-\infty} \cdot \mathrm{d}t_n
\cdot \int_{-\infty}^{+\infty} \mathrm{d}\tilde{t}_1 \cdots \int_{-\infty}^{+\infty} \cdot \mathrm{d}\tilde{t}_l \cdot \int^{ +\infty}_{-\infty} \mathrm{d}\bar{t}_1 \cdots \int_{-\infty}^{ +\infty} \cdot \mathrm{d}\bar{t}_m \\
&\Theta (t_1-t) \cdots \Theta(t_n-t) \cdot T_{\varepsilon}\left\{ V_D(t_1) V_D(t_2 ) \cdots V_D(t_n) \right\} \\
&\cdot \Theta(t-\tilde{t}_1) \Theta(\tilde{t}_1-t')\cdots  \Theta(t-\tilde{t}_l) \Theta(\tilde{t}_l-t') \cdot T_{\varepsilon}\left\{A_D(t) V_D(\tilde{t}_1) V_D(\tilde{t}_2 ) \cdots V_D(\tilde{t}_l)B_D(t') \right\} \\
&\cdot\Theta (t'-\bar{t}_1) \cdots \Theta(t'-\bar{t}_m)\cdot T_{\varepsilon}\left\{ V_D(\bar{t}_1) V_D(\bar{t}_2 ) \cdots V_D(\bar{t}_m) \right\} \\
&\cdot e^{-\alpha(|t_1|+\cdots |t_n| +|\tilde{t}_1| +\cdots| \tilde{t}_l| +|\bar{t}_1| + \cdots| \bar{t}_m|)}
\end{align*}
而
\begin{align*}
&\Theta (t_1-t) \cdots \Theta(t_n-t) \cdot T_{\varepsilon}\left\{ V_D(t_1) V_D(t_2 ) \cdots V_D(t_n) \right\} \\
&\cdot \Theta(t-\tilde{t}_1) \Theta(\tilde{t}_1-t')\cdots  \Theta(t-\tilde{t}_l) \Theta(\tilde{t}_l-t') \cdot T_{\varepsilon}\left\{A_D(t) V_D(\tilde{t}_1) V_D(\tilde{t}_2 ) \cdots V_D(\tilde{t}_l)B_D(t') \right\} \\
&\cdot\Theta (t'-\bar{t}_1) \cdots \Theta(t'-\bar{t}_m)\cdot T_{\varepsilon}\left\{ V_D(\bar{t}_1) V_D(\bar{t}_2 ) \cdots V_D(\bar{t}_m) \right\}
\end{align*}
是
\begin{align}
\label{eq:1to}
\cdot T_{\varepsilon}\left\{ V_D(t_1) V_D(t_2 ) \cdots V_D(t_n)  \cdot A_D(t) V_D(\tilde{t}_1) V_D(\tilde{t}_2 ) \cdots V_D(\tilde{t}_l)B_D(t')
\cdot  V_D(\bar{t}_1) V_D(\bar{t}_2 ) \cdots V_D(\bar{t}_m) \right\}
\end{align}
中的一部分, 三个 time-ordering 中共有 $m!n!l!$ 项, \eqref{eq:1to} 中共有 $(m+n+l)!$ 项. 每一个积分都是相互独立的, 所以这些项的积分结果都是相同的. 那么就有
\begin{align*}
&  U_{\alpha}^D(+\infty ,0) T_{\varepsilon}(U^D(0,t) A^D(t) U^D(t,t') B^D(t') U^D(t',-\infty)) \\
=&  \sum_{n,m,l=0}^{\infty}\frac{1}{n!m!l!} \cdot \frac{n!m!l!}{(n+m+l)!}\cdot \left( \frac{1}{\mathrm{i}\hbar} \right)^{n+m+l} \cdot \int^{+\infty}_{-\infty} \mathrm{d}t_1 \cdots \int^{ +\infty}_{-\infty} \cdot \mathrm{d}t_n
\cdot \int_{-\infty}^{+\infty} \mathrm{d}\tilde{t}_1 \cdots \int_{-\infty}^{+\infty} \cdot \mathrm{d}\tilde{t}_l \cdot \int^{ +\infty}_{-\infty} \mathrm{d}\bar{t}_1 \cdots \int_{-\infty}^{ +\infty} \cdot \mathrm{d}\bar{t}_m \\
& \cdot T_{\varepsilon}\left\{ V_D(t_1) V_D(t_2 ) \cdots V_D(t_n)  \cdot A_D(t) V_D(\tilde{t}_1) V_D(\tilde{t}_2 ) \cdots V_D(\tilde{t}_l)B_D(t')
\cdot  V_D(\bar{t}_1) V_D(\bar{t}_2 ) \cdots V_D(\bar{t}_m) \right\} \\
&\cdot e^{-\alpha(|t_1|+\cdots |t_n| +|\tilde{t}_1| +\cdots| \tilde{t}_l| +|\bar{t}_1| + \cdots| \bar{t}_m|)} \\
=&  \sum_{n,m,l=0}^{\infty}\frac{1}{n!m!l!} \cdot \frac{n!m!l!}{(n+m+l)!}\cdot \left( \frac{1}{\mathrm{i}\hbar} \right)^{n+m+l} \cdot \int^{+\infty}_{-\infty} \mathrm{d}t_1 \cdots \int^{ +\infty}_{-\infty} \cdot \mathrm{d}t_n
\cdot \int_{-\infty}^{+\infty} \mathrm{d}\tilde{t}_1 \cdots \int_{-\infty}^{+\infty} \cdot \mathrm{d}\tilde{t}_l \cdot \int^{ +\infty}_{-\infty} \mathrm{d}\bar{t}_1 \cdots \int_{-\infty}^{ +\infty} \cdot \mathrm{d}\bar{t}_m \\
& \cdot T_{\varepsilon}\left\{ V_D(t_1) V_D(t_2 ) \cdots V_D(t_n)  \cdot  V_D(\tilde{t}_1) V_D(\tilde{t}_2 ) \cdots V_D(\tilde{t}_l)B_D(t')
\cdot  V_D(\bar{t}_1) V_D(\bar{t}_2 ) \cdots V_D(\bar{t}_m) A_D(t)B_D(t')\right\} \\
&\cdot e^{-\alpha(|t_1|+\cdots |t_n| +|\tilde{t}_1| +\cdots| \tilde{t}_l| +|\bar{t}_1| + \cdots| \bar{t}_m|)}
\end{align*}
最后一个等号将 $A_D(t)B_D(t')$ 移到最后是因为相互作用 $V_D$ 中有偶数个产生湮灭算符, 所以在 time-ordering 中移动偶数个产生湮灭算符不改变符号.
如果换一个变量的名称, 令 $m+n+l\to n$ , $t, \tilde{t}, \bar{t}$ 也都 统一换成 $t$ ,那么就有
\begin{align*}
&  U_{\alpha}^D(+\infty ,0) T_{\varepsilon}(U^D(0,t) A^D(t) U^D(t,t') B^D(t') U^D(t',-\infty)) \\
=&  \sum_{n=0}^{\infty}\frac{1}{n!} \cdot \left( \frac{1}{\mathrm{i}\hbar} \right)^{n} \cdot \int^{+\infty}_{-\infty} \mathrm{d}t_1 \cdots \int^{ +\infty}_{-\infty} \cdot \mathrm{d}t_n
 \cdot T_{\varepsilon}\left\{ V_D(t_1)  \cdots V_D(t_n) A_D(t)B_D(t')\right\}\cdot e^{-\alpha(|t_1|+\cdots |t_n| )}
\end{align*}

* 零温单粒子因果格林函数

将前面三个 time-ordering 合并之后的结果代入到格林函数的定义中有
\begin{align*}
\mathrm{i} G_{AB}^c (t-t') =& \frac{ \langle \tilde{E}_0' | T_{\varepsilon}(A(t)B(t')) |\tilde{E}_0 \rangle}{\langle \tilde{E}_0 |\tilde{E}_0' \rangle}\\
=& \lim_{\alpha \to 0} \frac{\langle \eta_0| U_{\alpha}^D(+\infty ,0) T_{\varepsilon}(U^D(0,t) A^D(t) U^D(t,t') B^D(t') U^D(t',-\infty))| \eta_0\rangle}
{\langle \eta_0| U_{\alpha}^D(+\infty, -\infty)| \eta_0\rangle}\\
=& \lim_{\alpha \to 0} \frac{1}
{\langle \eta_0| U_{\alpha}^D(+\infty, -\infty)| \eta_0\rangle}\sum_{n=0}^{\infty}\frac{1}{n!}
\cdot \left( \frac{1}{\mathrm{i}\hbar} \right)^{n} \cdot \int^{+\infty}_{-\infty} \mathrm{d}t_1 \cdots \int^{ +\infty}_{-\infty} \cdot \mathrm{d}t_n
 \cdot  e^{-\alpha(|t_1|+\cdots |t_n| )} \langle \eta_0| T_{\varepsilon}\left\{ V_D(t_1) \cdots V_D(t_n) A_D(t)B_D(t')\right\} | \eta_0\rangle
\end{align*}

对于单粒子格林函数来说 $A(t)B(t')$ 为 $a_{\vec{k}\sigma }(t)a^{\dagger}_{\vec{k}\sigma}(t')$ ,即
\begin{align*}
&\mathrm{i} G_{\vec{k}\sigma}^c (t-t')\\
=& \lim_{\alpha \to 0} \frac{1}
{\langle \eta_0| U_{\alpha}^D(+\infty, -\infty)| \eta_0\rangle}\sum_{n=0}^{\infty}\frac{1}{n!}
\cdot \left( \frac{1}{\mathrm{i}\hbar} \right)^{n} \cdot \int^{+\infty}_{-\infty} \mathrm{d}t_1 \cdots \int^{ +\infty}_{-\infty} \cdot \mathrm{d}t_n
 \cdot  e^{-\alpha(|t_1|+\cdots |t_n| )} \langle \eta_0| T_{\varepsilon}\left\{ V_D(t_1) \cdots V_D(t_n) a_{\vec{k}\sigma }(t)a^{\dagger}_{\vec{k}\sigma}(t') \right\} | \eta_0\rangle
\end{align*}
上式对应于零温情况. $a_{\vec{k}\sigma }(t)a^{\dagger}_{\vec{k}\sigma}(t')$ 是 Dirac 表象下的算符, 由无相互作用 Hamiltonian $H_0$ 演化.
