#+TITLE: 研三下学期总结
#+DATE: <2020-09-07>
#+CATEGORIES: 想说
#+TAGS: 总结
#+HTML: <!-- toc -->
#+HTML: <!-- more -->

* 序

在家里过了一个学期. 现在虽然开学了, 但是还是去不了北园.

* 课题

完成了主要的数值计算部分(在忽略自能实部的情况下). 用 python 写了一个比较规范的程
序. Fortran 也写了. 两个程序的结果一致. 写的过程中遇到一些麻烦, 但都在老师的帮助
下解决了.

完善了 note. 从 rf 谱的定义出发, 推出了它与格林函数的关系. 计算格林函数的部分,
准确地对应到了费曼规则.

接下来的任务是推导 d 波和 p 波的分子格林函数, 以及验证粒子数分布的 tail .

* 读书

读书会读了量子光学. 毕竟在家读的, 书也写得比较简洁. 我的收获可以忽略.

Zee 的群论书基本算是过完一遍了. 挑了会用到的部分仔细看了. 如果以后再用到某些部分,
再回去仔细推导即可.

Weinberg 的书看了第二章 Poincare 代数的部分, 终于知道了如何用群论的知识推导出标
准模型的各种粒子是一个什么思路. 照这个进度, 年底是不可能看完了. 不过近期也不打算
继续看了. 

暑假(话说由于疫情, 貌似原本应该放假的, 但是也借助现代科技的力量而进行线上讨论,
就没有放假了...)开始的 Simons 的书, 仔细地看完了第二章, 前瞻性好浏览到第四章.

还做了光学助教. 也就是说, 把上课的作业都跟着做了一遍, 算上对本科没有好好学的一种
弥补吧.

* 业余

毕竟在家也没法成天学习, 于是开发各种兴趣爱好. 不仅有些付储了实践, 更多的都放在了
B 站的吃灰收藏夹里了. 同时貌似我也多了一个兴趣爱好: 看各种教学视频. 即使没有去实
践也很有意思. 比如爵士鼓的教学, 我买不起也没地方放, 但是看了一些入门视频知道了一
套鼓组有什么鼓, 有哪些比较基本的节奏. Bass 我估计也不会去弹, 但看教学视频了解了
自己经常听到但很陌生的东西.

寒假地时候, 学了一把 Django, 很爽! 做好了诗词网站放到了 saba.fun 上面. 但是由于
要线上开学, 此项目也迫中止. 学习 Django 有一个对 "正业" 的好处, 那就是在这里怎么
组织程序, 写标准的程序, 用到了写课题的程序中.

卡林巴琴. 用它弹了带伴奏的小星星. 原来钢琴就是这么给配的伴奏. 小巧有趣的乐器.

看完了多年前就想看的 Yale 的聆听音乐公开课, 还买了书. 收获很大. 被教授所折服. 正
如教授最后说的, 这门课并不是真正地在讲如何聆听音乐, 而是在向大家推广古典音乐. 但
是其中许多东西在各种音乐都是一样的. 这也一定程度上弥补了我在中小学时候缺失的音乐
鉴赏课程. 中小学从来没有人认真地讲如何鉴赏音乐.

数位板. ctl-472 . 做助教写答案, 顺便画画. 讲主文献课的时候也用的. 还是很有意思的.
也由于发现了一个特别优秀的开源软件 Krita! 数位板是不会白买的, 即使不画画, 也可以
联电脑手写笔记.

文明6. 好几年前玩过一局文明五, 基本忘得差不多了. 还和 s 哥进行了联机. 人生何其短
暂, 只有游戏才能让人去体验不一样的人生, 去体验帝国兴衰. 从水下第一个生命萌芽...
你已经历许多... 

618 的时候买了 Kindle Oasis 来代替大二时的入门版(放在学校了没带回家). 

然后买了铃木 scx64 . 不得不说, 第一次吹半音阶时, 那用声音的饱满, 低音区的震动真
的棒. 练了一段时间, 还是亏在了乐理上.

BanG Dream! 兴趣使然的游戏, 却无法自拔! 让没有学过音乐的我, 体验到演奏节奏的兴奋
与机动. 那种感觉, 没错, 就是 キラキラ　ドキドキ　！

玩了剑玉, 现在能稳定 皿上来回 了, 止剑成功率大约在 20% .

水果 FL Studio. 多年以前玩过 Cubase. 先是在 Manjaro 上 Ardor, 但是网上基本没有教
程. 之后知道 FL Studio 对鼠标党有友好, 因此用它来入门. 过段时间, 如果安顿下来,
可以考虑买个 midi 键盘. 编曲是个非常有趣的东西, 其中的乐趣就和写程序差不多, 但
是又更容易与人分享成果. 期间了解到 Wiwi , 是让我佩服的人.

将来哪一天我抑郁了, 上面这些杂七杂八的东西中的某一个, 或许会拯救我的余生, 成为我
活下去的理由.

* 总

感觉这学期什么也没有做, 什么也没做好. 但是回想起来还是有这么多的东西. 很意外地在
家里待了这么长的时间, 貌似是我从高一之后, 在家最长的一段时间. 感觉对家里的人更熟
悉了, 许多以前我没有了解他们的一些方面. 

不知疫情何时结束, 能够回到 2019 年冬天之前的那个世界.
