#+TITLE: 研三上学期总结
#+DATE: <2020-01-27>
#+CATEGORIES: 想说
#+TAGS: 总结
#+HTML: <!-- toc -->
#+HTML: <!-- more -->

* 序

吐嘈一下。这个网也不知道是怎么回事，笔记本上 clone 备份的博客一直卡，直到今天才
把备份下载下来，更新这篇。这按说应该是放假前的，今天都大年初三了！

这是第一次写学期总结。之所以这样做，是因为之前几个学期，过了几个学期之后，总是觉
得什么也没做。所以，记录一下，过几年再看，到底是真的什么也没做，还是仅仅是错觉。

* 课题

课题还在算 RF 谱。在研二下的时候重复了 Junjun Xu 的 PRA，推导了重整化关系。

从暑假开始，进行那篇 NSR 的数值计算。一开始用的 Python，之后由于老师不用 Python，
转用 Fortran，终于在本学期末的时候在不计算 $\Pi$ 的近似下基本重复出了文献中的几张
图。但是对于其中的物理意义不是很清楚，程序也写得很混乱，感觉做得有些失败。

之后开展自己的工作，起了个头，把 Note 写了，大体思路也明白了，知道大概要算什么。
在各种近似下，还是卡在了一个二重积分上！原因是积分的区间有跳变，打算解析地算出积
分边界，这是下个学期一开始的任务

* 读书

跟着读书会读了 PRML 的前五章，前边的部分还行，四五章也就只限于了解一个大概。如果
再有机会，要把 github 上的程序重复一遍，不然感觉这一学期就白读了。

又去听了三四次 HZ 的课。是 BEC-BCS Crossover 那一部分，收获颇丰！还有几节课的录
音没有整理。但是对于物理概念的提升很大。借此机会，也终于跨过了二次量子化，场算符
这道坎！

在学期末的时候还打算在2020年一年的时间里，过一遍 Weinberg 的 QFT 。现在看起来是
有些挑战性了。因为前置不足，又拾起了 A. Zee 的群论书，从头过了一下，大概到 SU(N)
群那里。所以群论也又复习，不，是又学习了一下。

还学习了 Fortran 。

* 业余

写博客的频率我还是很满意的。不知不学都写了一年了。

快放假的时候买了一本 Python 书，竞然用三五天的时间就把前面的部分，还有最后做 web
的实战做完了，还是很开心的。

又买了十年的域名。。。 saba.fun  还挺便宜的。目前备案正在审核。
