#+TITLE: 关于泛函的一些常识
#+DATE: <2020-05-18>
#+CATEGORIES: 专业笔记
#+TAGS: 数学
#+HTML: <!-- toc -->
#+HTML: <!-- more -->

* 前言

经常碰到, 将对泛的一些认识整理在这里, 以便查找.

* Definition 

通俗地讲, function 的输入是一个数, 输出也是一个数. functional 输入的是一个
function, 输出是一个数
\begin{align}
\mathrm{Function:}&\quad\quad  \mathrm{number: 3} 
\Rightarrow \mathrm{number: 27} \\
\mathrm{Functional:}&\quad\quad \mathrm{function:} \frac{e^xx^2}{3}
\Rightarrow \mathrm{number: 29}
\end{align}
更加形象的是 Blundell 书上的漫画.

* Example

functional $G[f]$ 做用到一个 funciton $f$ 上的结果如下
\begin{align}
  G[f] = \int_{-a}^a 5[f(x)]^2 \mathrm{d}x
\end{align}
那么如果给定一个 function $f(x) = x^2$ , 那么 functional 将会返回下面的 number 
\begin{align}
  G[f] = \int_{-a}^a 5x^4 \mathrm{d}x = 2a^5
\end{align}

* Functional Derivative

类似 function 的导数的定义, functional 的导数的定义如下
\begin{align}
  \frac{\delta F}{\delta f(x)} = \lim_{\epsilon\to 0} \frac{F[f(x') + \epsilon \delta(x - x')] - F[f(x')]}{\epsilon} 
\end{align}

#+BEGIN_QUOTE
Example:

对于 functional $J[f] = \int [f(y)]^p\varphi(y) \mathrm{d}y$ ,它的泛函导数为
\begin{align}
  \frac{\delta J[f]}{\delta f(x)} = \lim_{\epsilon\to 0}\frac{1}{\epsilon}\left[  
    \int [f(y) + \epsilon \delta(y-x)]^p\varphi(y) \mathrm{d}y - \int [f(y)]^p\varphi(y) \mathrm{d}y
   \right]
\end{align}
是一个 $\frac{0}{0}$ 型的极限, 上下对 $\epsilon$ 求导得
\begin{align}
  \frac{\delta J[f]}{\delta f(x)} =& \lim_{\epsilon\to 0}\frac{1}{1}\left[  
    p\int [f(y) + \epsilon \delta(y-x)]^{p-1}\varphi(y)\delta(y - x) \mathrm{d}y 
   \right] \\
=& \left[  
    p\int f(y) ^{p-1}\varphi(y)\delta(y - x) \mathrm{d}y 
   \right] \\
=& p f(x) ^{p-1}\varphi(x)
\end{align}
与幂指数型的 function 求导有类似的结果.
#+END_QUOTE

#+BEGIN_QUOTE
Example:

对于 functional $F[f(x)] = \int_a^b g(f') \mathrm{d}x$ , 它的泛函导数为
\begin{align}
  \frac{\delta F[f]}{\delta f(x)} =& \lim_{\epsilon\to 0}
  \frac{1}{\epsilon}\left[  
    \int_a^b g[f'(y) + \epsilon \delta'(y-x)] \mathrm{d}y - \int_a^b g[f'(y)] \mathrm{d}y 
   \right] \\
  =& \lim_{\epsilon\to 0}
    \frac{\mathrm{d}}{\mathrm{d}\epsilon}\left[  
    \int_a^b g[f'(y) + \epsilon \delta'(y-x)] \mathrm{d}y 
   \right] \\
=&    \int_a^b \frac{\mathrm{d}g }{\mathrm{d}f'}
     \delta'(y-x) \mathrm{d}y  \\
\end{align}
上式中 $\delta'(y-x)$ 是没法处理的, 但是我们可以用分部积分法
\begin{align}
  \frac{\delta F[f]}{\delta f(x)} =&  \int_a^b \frac{\mathrm{d}g }{\mathrm{d}f'}
     \delta'(y-x) \mathrm{d}y  \\
   = & \left.\frac{\mathrm{d}g }{\mathrm{d}f'}
     \delta(y-x)\right|_{y=a}^{y=b} - 
 \int_a^b\mathrm{d}y \cdot \frac{\mathrm{d}}{\mathrm{d}x}\left( \frac{\mathrm{d}g }{\mathrm{d}f'} \right)
   \delta(y-x)
\end{align}
由于原来泛函中的积分区间是 $(a, b)$ , 所以 $y\in(a, b)$ 才有意义, 不然变分恒为零.
因此 $\delta(a-x) = \delta(b-x) = 0$ . 最终的泛函导数为
\begin{align}
  \frac{\delta F[f]}{\delta f(x)} =& - 
 \int_a^b\mathrm{d}y \cdot \frac{\mathrm{d}}{\mathrm{d}x}\left( \frac{\mathrm{d}g }{\mathrm{d}f'} \right)
   \delta(y-x) \\
  =& - \frac{\mathrm{d}}{\mathrm{d}x}\left( \frac{\mathrm{d}g }{\mathrm{d}f'} \right)
\end{align}
#+END_QUOTE



* Reference

- Tom Lancaster, Stephen J. Blundell, Quantum Field Theory for the Gifted
  Amateur, 2014, Oxford University Press


