#+TITLE: Term Symbol
#+DATE: <2020-04-16>
#+CATEGORIES: 专业笔记
#+TAGS: 物理, 电子组态
#+HTML: <!-- toc -->
#+HTML: <!-- more -->

* Term Symbol

Term Symbol 用来描述一个多电子原子的(总)角动量量子数, 也可以用来描述单个电子.

原子的每个能级不仅由 electron configuration(电子所处的轨道) 来描述, 也由 term
symbol 来描述. 因为原子的能级不仅仅依赖于 electron configuration, 还依赖于 它们
的总角动量(spin orbital coupling).

记号
\begin{align}
  ^{2S+1}L_{J}
\end{align}
$S$ 是总的自旋量子数. $2S+1$ 是 spin multiplicity, ( $L\le S$ 时)表示给定 $L, S$
时, $J$ 可能取值的个数. $L$ 是轨道量子数, $J$ 是总的角动量量子数.

* 用 Term Symbol 表示原子的基态

1. 找到最稳定的 electron configuration. 把 full shells and subshells 去掉, 因为
   它们对总角动量没有贡献. 比如
   对于 fluorine F , 第九号元素, 它的原子最稳定的组态是 $1s^22s^22p^{5}$ , 它的 $1s$
   和 $2s$ 轨道都被填满, $2p$ 轨道可以填六个电子, 这里只填了五个, 所以只用这个不
   満壳层的电子来表示原子的基态.
2. 由于 Pauli 不相容原理, $L=-1, 0 , 1$ 三个轨道上有两个填上一对自旋相反的电子,
   另一个轨道上只有一个电子. 根据 Hund's rule, 要让 $S, L$ 最大, 所以 $L=-1$ 是
   那个填一个电子的态. 这样, 总的自旋是 $1/2$ 总的轨道角动量是 $1$ .
3. 这样, 总的角动量 $J = 1/2$ 或者 $J=3/2$ .再根据 Hund's rule, $J=3/2$ 能量更低,
   所以它的基态为
\begin{align}
  ^2P_{\frac{3}{2}}
\end{align}

* Alkali Atoms

** 基态

Alkali atoms 在最外层的非满壳层只有一个电子, 那么它的基态就是这个电子在 $s$ 轨道
上, 所以 $S=1/2, L=0, J=1/2$ , 用 term symbol 表示就是 $^2S_{1/2}$ .

** 激发态

Alkali atoms 的激发态, 这个电子被激发到 $p$ 轨道上, 那么 $S=1/2, L=1, J=1/2$ ,或
者 $S=1/2, L=1, J=3/2$ , 用 term symbol 表示就是 $^2P_{1/2}$ 或者 $^2P_{3/2}$ .

* Alkaline-Earth(like) Atoms.

** 基态

Alkaline-Earth(like) Atoms 在最外层的非满壳层有两个电子, 那么它的基态, 两个电子都在 $s$ 轨道上,
所以 $S=0, L=0, J=0$ 用 term symbol 表示就是 $^1S_0$ .

所有 Boson 的碱土原子的同位素的 nuclear spin 都是 $0$ , 而 Fermion 都是非零的.

** 激发态

Alkaline-Earth(like) Atoms 的激发态, 一个电子待在 $s$ 轨道上, 另一个电子被激发到
$p$ 轨道上, 所以 $L=1$ , 根据 Hund's rule $S=1$ 的能量要比 $S=0$ 的能量低. 那么
有 $S=1, L=1, J=0, 1, 2$  用 term symbol 表示就是 $^3P_{0}, ^3P_{1}, ^3P_2$ .

由于 dipole transion 是不改变自旋的, 所以从基态到激发态是 spin forbidden 的. 它
耦合的是基态和 $^1P_1$ .

* Reference 

- [1] https://en.wikipedia.org/wiki/Term_symbol

