#+TITLE: 记一次折腾上头经历: lsp-pyright vs. flycheck & flake8
#+DATE: <2021-03-19>
#+CATEGORIES: 软件使用
#+TAGS: emacs, lsp, pyright, flycheck, flake8
#+HTML: <!-- toc -->
#+HTML: <!-- more -->

起因于昨天下午.

在科研课题久久没有进展之后, 突然有了一些想法. 遂写程序.

在寒假配置的 Emacs 个人新版配置终于有了用武之地, 甚是高兴.

可随后而来的却是一次折腾上头.

之前在 Emacs 里加了 lsp-pyright, 可以提示程序中一些不规范的细节. 比如给一行注释
的话要在 =#= 后面加至少两个空格, 诸如此类的根据 PEP8 给出的提示.

可是很奇怪, 它在笔记本上可以, 在台式上不行. 开始以为是设置工程前可以显示, 设置工
程路径后就不显示了. 这也很奇怪. 搞来搞去不行, emacs 的插件删了又重下, 好多次, 就
是不行. 基本断定不是 emacs 配置的原因. 想着放弃吧, 现在没那么多多余的时间搞这些
了. 于是昨天搞了一晚上后回宿舍睡觉了.

第二天上自习, 还是忍不住, 又搞了起来, 发现并不是设置工程路径的原因. 各种查 lsp,
原理, 配置...

未果.

越来越上头了. 今天下午为了做对照, 新建了用户, 发现和用户也没关系, 看来也不是 lsp
设置的原因.

最后, 尝试安装 KDE 版本的 manjaro. 一开始想试一下直接 arch, 但想想还是算了. 没想
到装 manjaro 也是出了问题, 第一次装完, 莫名其妙地少了 libc.so , 连 pacman 都打不
开了. 想了个笨方法 chroot 直接复制 libc.so 文件直接过去, 结果连 kernel 也进不去
了.

那就再装一次吧, 我已经无法回头了. 期间还出现了少见的办公室断网, 这运气...

第二次终于好了, 验证了没有显示 PEP8 提示的原因是少装了什么软件.

最后终于发现是 flycheck 调用 pylint 给的提示, 和 lsp 没一点关系! 安上 flake8 就
好了.

太上头了. 自己本来就是外行程序员, 还这么喜欢搞这些, 下场就是一天半的时间没了...

不过也有收获. 那就是现在台式上以前丢失的引导在装了 KED manjaro 之后全部都找回来
了. 现在开机有五个系统可选.

本来想尝试 KDE 的, 可以就这一下午就出了致命和不致命的问题, 还是算了吧! 等我真正
闲的时候再尝试吧.

不过这次折腾有一个好的结果, 不是放弃了, 而是解决了. 问题解决了, 心情是真的舒畅,
真的爽!!!

这一切都不是因为问题有多复杂, 只是看问题缺乏知识, 流于表面. 或许科研也是这样, 大
家都这样, 就习以为常了.
