#+TITLE: 研四下学期总结
#+DATE: <2021-09-07>
#+CATEGORIES: 想说
#+TAGS: 总结
#+HTML: <!-- toc -->
#+HTML: <!-- more -->

* 序

前天返校, 昨天看了 Susskind 的三节视频.

* 课题

终于找到了动量分布的 tail 之前没有对上的原因. 原来大家的径向分布都没有带上体积因
子 $r^2$ . 看起来非常简单的原因, 却找了一个学期的时间. 虽然不算浪费时间, 但是也有
点惋惜. 找原因的思路是没有问题的, 那就是把 tail 是如何得到的推导一遍, 用自己数值
计算用的方法推导一遍.

找 tail 的原因, 又重复了一些经典的工作, 比如 s 波的 BEC-BCS crossover 的
$T_{\mathrm{C}}$ 随相互作用的曲线, 收获也很大.

收获一是在于理论上的方法, 期间参考了 Strinati 的那篇综述, 学到了很多知识, 对留数
定理的应用, 分析 pole 的位置.

收获二是在于数值方法上的, 为了探寻最有效的积分方法, 终于知道了 scipy.integrate
里面的 quad 方法是如何算的, 知道了它是上个世纪 80 年代就写成, 至今没有进一步更新
的 fortran 77 包 QUADPACK, 它综合了许多数值积分的方法, 可以用参数指定, 而最常用
的就是用两种 quadrature 方法点来计算, gsl 也有把 QUADPACK 的方法重新用 c++ 重写,
可以学习它的源码. 一般来讲, 给定函数计算低维的数值积分, 没有比这个更优化的方法,
关键就是针对特定的函数, 如何在一些发散的地方做一些处理. 所以用哪个语言都一样, 效
率都是这样, 因为 scipy 也是 fortran 写的. 了解了这些, 有种不惧任何数值积分的错觉...

* 读书

本学期组内读书会读的是 Ahtony Zee 的群论, 读了前三章, 回顾了一些知识.

Carl Bender 微扰公开课的第七节.

Athony Zee, Peskin & Schroeder 的两本量子场论认真地看了开头, 后面也非常粗率地浏
览了一下, 大致了角了高能物理在研究什么.

最令人振奋的是看了 Susskind 的一系列视频, 这才真的是宝藏! 即使之前学过的知识, 再
听他讲也非常有收获. 没学过的, 只要认真听, 都是了解大概的脉络. 看了他的课, 我才意
识到, 书本和讲课的本质区别. 讲课在于, 用最容易理解的语言, 最简单, 不求严谨的例子,
讲清最核心的概念, 激发出求知的欲望, 掌握整体的框架. 而书本在于, 在求知欲的引导下,
填满那些课堂上缺失的细节, 做习题熟悉概念. 只听课容易空旷, 只看书容易迷失. 这样明
显的道理, 我是悟到地有一点晚了. 目前看了 Susskind 的 quantum mechanics,
classical field theory, statistical mechanics, particl physic I, particle physic
II.

还发现了 Wolfgang Ketterle 的 AMO 公开课, 由于时间关系, 只看了两节. 之后还会再看.

* 业余

在校期间没怎么发展爱好, 唯一的休闲是打邦邦, 直到暑假的时候, 我发现我最高都可以打
过 28 的曲子了, 之前从没想到的六兆年也部分可打, 真就是形成肌肉记忆了, 时间的力量
真是强大!

在青岛开会学习也很开心!

八月在暑假在家一个月, 完全没学物理. 买了一把吉他 Yamaha F310 练了一个月, 这一个
月练习算是比较多了, 成果也还满意. 吉他成为我心中最易初学的乐器, 有人初学音乐, 吉
他是首选:

- 相比钢琴, 键盘等, 它体积小, 不用插电, 在哪都能弹, 方便 max!

- 相比口琴, 弹吉他不用漱口, 可以吃着东西弹, 而且长时间弹也不会腮邦子疼!

- 声音穿透没有口琴那么强, 不用担心扰民, 在家我可以深夜弹吉他, 口琴是绝对不能的!

- 发声简单! 只要按对弦, 就和键盘一样, 哪个音都是一样简单. 不像十孔口琴, 能吹出干
  净的单音就要一些练习, 许多曲子更是要压音, 超吹.

- 便于学习一些乐理.

在这个暑假里, 在旷野之息的世界里, 林克已经无所畏惧了, 爆头秒人马, 风弹満图飞.

* 总

一波总结下来, 这学期还真是充实. 但是, 课题还是没有做完! 这次奖学金我又要蝉联三等
了...

新学期是真正的, 没有一门课要上的学期! 做了冷原子助教, 希望这次能花时间认认真真地
学一下.

last but not least, 我都五年级了, 课题, 抓紧!
